version: "3"

services:
  drzl-pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: LdsfgjpmLDSFg8941sdfgsdfc
      POSTGRES_USER: root
      POSTGRES_DB: pgs_database
    ports:
      - "5432:5432"
    volumes:
      - drzl-pg-data:/var/lib/postgres

  drzl-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - drzl-redis-data:/data

  app:
    image: myimage:l3.8.3
    environment:
      POSTGRES_PASSWORD: LdsfgjpmLDSFg8941sdfgsdfc
      POSTGRES_DB: pgs_database

    env_file:
      - .env.development
    ports:
      - "3000:3000"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    depends_on:
      - drzl-pg
      - drzl-redis

volumes:
  drzl-pg-data:
  drzl-redis-data:
  node_modules:
